IF(UNIX)
    FIND_PATH(CPP_REST_INCLUDE_DIR http_client.h
        /usr/include/cpprest
    )
    MESSAGE(STATUS "Found CPP_REST_INCLUDE_DIR: ${CPP_REST_INCLUDE_DIR}")

    SET(CMAKE_FIND_LIBRARY_PREFIXES "" "lib")
    SET(CMAKE_FIND_LIBRARY_SUFFIXES ".so" ".a" ".lib")
    FIND_LIBRARY(CPP_REST_LIBRARY NAMES cpprest PATHS
      /usr/lib
    )
    MESSAGE(STATUS "Found CPP_REST_LIBRARY: ${CPP_REST_LIBRARY}")

ELSE()
    #use vcpkg on Win and automatic find_package
ENDIF()


IF (CPP_REST_INCLUDE_DIR AND CPP_REST_LIBRARY)
    SET(CPP_REST_FOUND TRUE)
ENDIF (CPP_REST_INCLUDE_DIR AND CPP_REST_LIBRARY)

IF (CPP_REST_FOUND)
    MESSAGE(STATUS "Found C++ REST: ${CPP_REST_LIBRARY}")
ELSE (CPP_REST_FOUND)
    MESSAGE(FATAL_ERROR "Could not find C++ REST")
ENDIF (CPP_REST_FOUND)

